version: "3.8"

services:
  localrun:
    image: delcagox/dwd-coursepage:latest
    container_name: container_local
    ports:
      - 127.0.0.1:8080:8080
  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower 
