
name: Release NodeJS app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: 
          docker build . -t devopsdockeruh/coursepage:latest          
      
      - name: publish
        run: 
          docker login -u delcagox -p ${{ secrets.DOCKERHUB_TOKEN }} 
          docker push delcagox/devopswithdockeruh/coursepage:latest
      
      # ...